services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - ./server/db/db_dumps/stonkinator.sql:/docker-entrypoint-initdb.d/datadump.sql
      - securities_data:/var/lib/postgresql/data
    ports:
      - ${PG_DB_PORT_EXP}:${PG_DB_PORT}

  http_api:
    depends_on:
      - ${PG_DB_SERVICE}
    environment:
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_SERVICE: ${PG_DB_SERVICE}
      API_URL: ${API_URL}
      STONKINATOR_API_PORT: ${STONKINATOR_API_PORT}
    build: ./server
    ports:
      - ${STONKINATOR_API_PORT_EXP}:${STONKINATOR_API_PORT}
    develop:
      watch:
        - action: rebuild
          path:
            ./server/src

  rpc_service:
    depends_on:
      - ${PG_DB_SERVICE}
    environment:
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_SERVICE: ${PG_DB_SERVICE}
      RPC_SERVICE_PORT: ${RPC_SERVICE_PORT}
    build:
      context: ./stonkinator
      dockerfile: Dockerfile.rpc_service
    develop:
      watch:
        - action: rebuild
          path:
            ./stonkinator/rpc_service/src

  stonkinator:
    depends_on:
      - ${STONKINATOR_API_SERVICE}
      - ${STONKINATOR_RPC_SERVICE} 
    environment:
      API_HOST: ${STONKINATOR_API_SERVICE}
      RPC_SERVICE_HOST: ${STONKINATOR_RPC_SERVICE}
      API_PORT: ${STONKINATOR_API_PORT}
      RPC_SERVICE_PORT: ${RPC_SERVICE_PORT}
      LOG_DIR_PATH: ${LOG_DIR_PATH}
      TS_HANDLER_DIR_TARGET: ${TS_HANDLER_DIR_TARGET}
    build:
      context: ./stonkinator
      dockerfile: Dockerfile.stonkinator
    volumes:
      - ./stonkinator/stonkinator:/app

  # frontend:
  #   depends_on:
  #     - ${STONKINATOR_API_SERVICE}
  #   build: ./stonkinator_frontend
  #   ports:
  #     - ${FRONTEND_PORT}:${FRONTEND_PORT}
  #   volumes:
  #     - ./stonkinator_frontend/src:/app/src

volumes:
  securities_data:
  stonkinator_data:
