services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    volumes:
      - ./db/db_dumps/stonkinator.sql:/docker-entrypoint-initdb.d/datadump.sql
      - securities_data:/var/lib/postgresql/data
    ports:
      - ${PG_DB_PORT_EXP}:${PG_DB_PORT}

  web_api:
    depends_on:
      - ${PG_DB_SERVICE}
    environment:
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_SERVICE: ${PG_DB_SERVICE}
      API_URL: ${API_URL}
      WEB_API_PORT: ${WEB_API_PORT}
      WEB_API_KEY_PATH: ${WEB_API_KEY_PATH}
      WEB_API_CERT_PATH: ${WEB_API_CERT_PATH}
    build: ./web_api
    ports:
      - ${WEB_API_PORT_EXP}:${WEB_API_PORT}
    develop:
      watch:
        - action: rebuild
          path:
            ./web_api/src

  rpc_service:
    depends_on:
      - ${PG_DB_SERVICE}
    environment:
      PG_DB_USER: ${PG_DB_USER}
      PG_DB_PORT: ${PG_DB_PORT}
      PG_DB_PASSWORD: ${PG_DB_PASSWORD}
      PG_DB_NAME: ${PG_DB_NAME}
      PG_DB_SERVICE: ${PG_DB_SERVICE}
      RPC_SERVICE_PORT: ${RPC_SERVICE_PORT}
      RPC_SERVER_KEY_PATH: ${RPC_SERVER_KEY_PATH}
      RPC_SERVER_CERT_PATH: ${RPC_SERVER_CERT_PATH}
      RPC_SERVICE_CA_CERT_PATH: ${RPC_SERVICE_CA_CERT_PATH}
    build:
      dockerfile: Dockerfile.rpc_service
    develop:
      watch:
        - action: rebuild
          path:
            ./rpc_service/src

  data_frame_service:
    build:
      dockerfile: Dockerfile.data_frame_service
      args:
        PROTOBUF_DIR: ${PROTOBUF_DIR}
        PROTOBUF_PACKAGE: ${PROTOBUF_PACKAGE}
        DF_SERVICE_HOST: ${DF_SERVICE_HOST}
        DF_SERVICE_PORT: ${DF_SERVICE_PORT}
    ports:
      - ${DF_SERVICE_PORT}:${DF_SERVICE_PORT}

  stonkinator:
    depends_on:
      - ${STONKINATOR_RPC_SERVICE} 
      - ${STONKINATOR_DF_SERVICE} 
    environment:
      RPC_SERVICE_HOST: ${STONKINATOR_RPC_SERVICE}
      RPC_SERVICE_PORT: ${RPC_SERVICE_PORT}
      RPC_SERVICE_KEY_PATH: ${RPC_SERVICE_KEY_PATH}
      RPC_SERVICE_CERT_PATH: ${RPC_SERVICE_CERT_PATH}
      RPC_SERVICE_CA_CERT_PATH: ${RPC_SERVICE_CA_CERT_PATH}
      DF_SERVICE_HOST: ${STONKINATOR_DF_SERVICE}
      DF_SERVICE_PORT: ${DF_SERVICE_PORT}
      LOG_DIR_PATH: ${LOG_DIR_PATH}
      TS_HANDLER_DIR_TARGET: ${TS_HANDLER_DIR_TARGET}
    build:
      dockerfile: Dockerfile.stonkinator
      args:
        PROTOBUF_DIR: ${PROTOBUF_DIR}
        PROTOBUF_PACKAGE: ${PROTOBUF_PACKAGE}
    # volumes:
    #   - ./stonkinator/stonkinator:/app

volumes:
  securities_data:
  stonkinator_data:
